# Generated by Django 4.2.26 on 2025-11-14 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_accion', models.CharField(blank=True, max_length=150, null=True)),
                ('accion', models.CharField(max_length=20)),
                ('modelo_afectado', models.CharField(max_length=100)),
                ('instancia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('data_anterior', models.JSONField(blank=True, null=True)),
                ('data_nueva', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'db_table': 'NUAM_BITACORA_AUDITORIA',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador de Negocio'), ('CONTADOR', 'Contador / Operador')], default='CONTADOR', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'db_table': 'NUAM_PERFILES_USUARIO',
            },
        ),
        migrations.CreateModel(
            name='DocumentoFuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_fuente/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel')], max_length=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Fuente',
                'db_table': 'NUAM_DOCUMENTOS_FUENTE',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corredor', models.CharField(db_index=True, max_length=150)),
                ('anio_tributario', models.IntegerField(db_index=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('f8', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Factor F8')),
                ('f9', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Factor F9')),
                ('f10', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Factor F10')),
                ('f19', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Factor F19')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('documento_respaldo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calificaciones.documentofuente')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'NUAM_CALIFICACIONES',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
