# Generated by Django 4.2.26 on 2025-11-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='f11',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Factor F11'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='f12',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Factor F12'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='f13',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Factor F13'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='f14',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Factor F14'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='f15',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Factor F15'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='f16',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Factor F16'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='f17',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Factor F17'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='f18',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Factor F18'),
        ),
    ]
