# Generated by Django 4.2.26 on 2025-11-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_calificacion_f11_calificacion_f12_calificacion_f13_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='anio_tributario',
            field=models.IntegerField(db_index=True, verbose_name='Año Tributario'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador de Negocio'), ('CONTADOR', 'Contador / Trabajadorr')], default='CONTADOR', max_length=20),
        ),
    ]
