# Generated by Django 4.2.26 on 2025-11-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_alter_calificacion_anio_tributario_alter_perfil_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='anio_tributario',
            field=models.IntegerField(db_index=True, verbose_name='Anio Tributario'),
        ),
    ]
