# Generated by Django 4.2.26 on 2025-11-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_alter_calificacion_anio_tributario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='anio_tributario',
            field=models.IntegerField(db_index=True, verbose_name='Año Tributario'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='corredor',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Corredor'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto'),
        ),
    ]
