# Generated by Django 4.2.27 on 2025-12-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0005_alter_calificacion_anio_tributario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador de Negocio'), ('CONTADOR', 'Contador / Trabajador')], default='CONTADOR', max_length=20),
        ),
    ]
